@startuml

-> ":CapCommandParser" ++ : CapCommand()
    ":CapCommandParser" -> ":CapCommand" ** : <<construct>>
    activate ":CapCommand"
    return
<-- ":CapCommandParser" !! : CapCommand

-> ":CapCommand" ++ : execute()
    ":CapCommand" -> ":CapCommand" ++ : calculateCap()
        |||
        participant ":ModuleManager" as MM << Class >>
        ":CapCommand" -> MM ++ : getModuleMap()
        return moduleList
        |||
        ":CapCommand" -> ":CapCommand" ++ : gradeConvert(moduleList)
        return mcGrade
        |||
    return CAP

    create ":CommandResult"
    ":CapCommand" -> ":CommandResult" ++ : <<construct>>
    return CommandResult
<-- ":CapCommand" !! : CommandResult
@enduml