@startuml


abstract class Command {
    PromptType promptType
    PromptType getPromptType()
    void setPromptType()
    CommandResult execute()
}

class CommandResult {
    String feedbackToUser
}

abstract class AddCommand
class AddModuleCommand
class AddTaskCommand

abstract class DeleteCommand
class DeleteModuleCommand
class DeleteTaskCommand

abstract class EditCommand
class EditModuleCommand
class EditTaskCommand

abstract class TimeTableCommand
class TimeTableAddCommand
class TimeTableDeleteCommand
class TimeTableViewCommand

class DoneCommand
class UndoCommand
class HelpCommand
class ListCommand
class ExitCommand
class IncorrectCommand
enum PromptType {
    WARNING,
    INFORMATIVE,
    NONE,
    EDIT
}

Command <|- HelpCommand
Command <|- ListCommand
Command <|- ExitCommand
Command <|-- DeleteCommand
Command <|-- AddCommand
EditCommand ---|> Command
DoneCommand -|> Command
UndoCommand -|> Command
IncorrectCommand -|> Command
TimeTableCommand ---|> Command

PromptType -* Command

Command <. CommandResult

AddCommand <|-- AddModuleCommand
AddCommand <|-- AddTaskCommand

DeleteCommand <|-- DeleteModuleCommand
DeleteCommand <|-- DeleteTaskCommand

EditModuleCommand --|> EditCommand
EditTaskCommand --|> EditCommand

TimeTableAddCommand --|> TimeTableCommand
TimeTableDeleteCommand --|> TimeTableCommand
TimeTableViewCommand --|> TimeTableCommand

@enduml