@startuml

hide circle
skinparam classAttributeIconSize 0

class Executor
class Scanner

package parser {
    class Parser
}

package command {
    class Command
    class CommandResult
}

package data {
    class InputOutputManager
    class StateManager
}

package ui {
    class TextUi {
        Scanner in
    }
}

Ravi .> ui
Ravi ..> Executor
Ravi ...> data
Ravi ..> command

Executor ..> parser
parser ..> command
Executor ..> command

TextUi "1" *-- Scanner

@enduml