@startuml
mainframe sd startCommandLoop()

participant ":Executor" as Ex << Class >>
participant ":TextUi" as Ui << Class >>
participant ":Parser" as P << Class >>
participant ":InputOutputManager" as IO << Class >>
participant ":StateManager" as State << Class >>

-> Ex ++ : startCommandLoop()

loop do while Exit command not received

    Ex -> Ui ++ : Get user input
    |||
    return User input string

    Ex -> Ex ++ : executeCommand()
        Ex -> P ++ : Parse user input
            P -> ":Command" ** : Construct relevant\nCommand
            activate ":Command"
                ":Command" -> ":CommandResult" ** : Construct\nCommandResult
                activate ":CommandResult"
                return CommandResult object
            return Command object
        return Command object

        Ex -> ":Command" ++ : Execute Command
        return CommandResult object
        destroy ":Command"
        |||

        opt If user made changes to data
            Ex -> IO ++ : Save data
            return

            Ex -> State ++ : Save state
            return
        end opt
    return CommandResult object

    Ex -> Ui ++ : Show CommandResult to user
    |||
    return

end loop
return

@enduml