@startuml

participant ":Ravi" as Ravi << Class >>

create Ravi
activate Ravi
-> Ravi: main()
Ravi -> Ravi ++ : Add shutdown hook
return
|||
Ravi -> Ravi  ++ : run()
    |||
        ref over Ravi: start()
        opt Could not load NUSMods
            |||
            <- Ravi : Terminate program here
        end opt
        |||
        ref over Ravi: runCommandLoopUntilExitCommand()
    |||
return

<- Ravi -- : exit main()

-> Ravi ++ : Shutdown hook
Ravi -> Ravi ++ : Print "saving" message
note right
    Saving is actually done in Executor.
    This is just to assure the user that
    ra.VI has shut down properly (if they
    used Ctrl-C to shut down ra.VI)
end note
return
return Completed shutdown
destroy Ravi

@enduml